### ISSUE TITLE
Steps to use with Arduino Esp8266 board

### ISSUE THREAD

**Issue by waghekapil** [nogoegst/bearssl#1]
Hello,

Thanks for the library.

Can you please guide me to use this library in Arduino SDK for ESP8266 board. I want to use it for AWS IoT secure MQTT connection.

AWS IoT supports TLS1.2.

**Comment by unkaktus** [comment]
Hi,
I am not an author of this library (this is mostly a mirror) nor I can help you with 8266. You can find all the information about this library at https://bearssl.org/.
HTH.
